image: gcc

build:
  stage: build
  before_script:
    - apt update && apt -y install make autoconf automake
  script:
    - autoreconf -vfi
    - ./configure
    - make

test:
  stage: test
  script:
    - make check
    - make distcheck
